# Site settings
title: Aprenda Grego Bíblico
header-img: img/home-bg.jpg
email: andre@andrescalco.com
copyright_name: "Aprenda Grego Bíblico"
description: "Aprenda Grego Bíblico é uma nova plataforma para lhe auxiliar no aprendizado do Grego Koinê"
baseurl: ""
url: "http://aprendagregobiblico.com.br"
twitter_username: andre_scalco
facebook_username:  aprendagregobiblico
email_username:  andre@andrescalco.com

# Google Analytics
google_tracking_id: UA-86274710-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
